# Generated by Django 6.0 on 2025-12-16 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sparerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_no', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('part_name', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('mrp', models.CharField(blank=True, max_length=50)),
                ('cc_remarks', models.CharField(default='ORDERED', max_length=100)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Out Order',
                'verbose_name_plural': 'Stock Out Orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_no', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('part_name', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('mrp', models.CharField(blank=True, max_length=50)),
                ('cc_remarks', models.CharField(default='RECEIVED', max_length=100)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_received', to=settings.AUTH_USER_MODEL)),
                ('stock_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_record', to='api.stockoutorder')),
            ],
            options={
                'verbose_name': 'Stock Received',
                'verbose_name_plural': 'Stock Received',
                'ordering': ['-received_at'],
            },
        ),
    ]
