# Generated by Django 6.0 on 2025-12-18 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_stockoutorder_complaint_no_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_spare_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sparerequest',
            name='complaint_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='complaint_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockreceived',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
