# Generated by Django 6.0 on 2025-12-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sparerequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreceived',
            name='complaint_no',
            field=models.CharField(max_length=100),
        ),
    ]
