# Generated by Django 6.0.3 on 2026-04-06 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_stockoutorder_complaint_no_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('technician_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('part_name', models.CharField(max_length=200)),
                ('quantity_reduced', models.IntegerField()),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('stock_reduced', models.BooleanField(default=True)),
                ('processing_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Processed Complaint',
                'verbose_name_plural': 'Processed Complaints',
                'ordering': ['-processed_date'],
                'indexes': [models.Index(fields=['complaint_no', 'processed_date'], name='proc_complaint_date_idx'), models.Index(fields=['technician_name', 'processed_date'], name='proc_tech_date_idx'), models.Index(fields=['stock_reduced'], name='proc_stock_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIRECT', 'Direct'), ('COMPLIANT', 'Compliant')], default='DIRECT', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('compliant_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_sales_requests', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Request',
                'verbose_name_plural': 'Sales Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.salesrequest')),
            ],
            options={
                'verbose_name': 'Sales Request Product',
                'verbose_name_plural': 'Sales Request Products',
            },
        ),
    ]
