# Generated by Django 6.1.1 on 2026-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fix_product_id_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hsn', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'spare_id'],
            },
        ),
        migrations.CreateModel(
            name='TrackingComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row_number', models.PositiveIntegerField(unique=True)),
                ('sheet_row_id', models.CharField(blank=True, max_length=100)),
                ('complaint_no', models.CharField(db_index=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('part_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('complaint_status', models.CharField(blank=True, max_length=50)),
                ('pending_days', models.CharField(blank=True, max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('technician_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('mrp', models.CharField(blank=True, max_length=50)),
                ('cc_remarks', models.CharField(blank=True, db_index=True, max_length=100)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sheet_row_number'],
                'indexes': [models.Index(fields=['complaint_status', 'technician_name'], name='tracking_status_tech_idx'), models.Index(fields=['cc_remarks'], name='tracking_remarks_idx')],
            },
        ),
    ]
