# Generated by Django 6.1.1 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_companystock_trackingcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingcomplaint',
            name='sheet_column_p',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
