# Generated by Django 6.1.1 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_trackingcomplaint_sheet_column_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('spare_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'spare_id'],
                'unique_together': {('technician_name', 'spare_id')},
                'verbose_name': 'Technician Stock Snapshot',
                'verbose_name_plural': 'Technician Stock Snapshots',
            },
        ),
    ]