import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

/**
 * Generate CSV content for sales report (Excel-compatible)
 */
const generateSalesReportCSV = (salesRequests) => {
  // Filter only approved requests and group by technician
  const approvedRequests = salesRequests.filter(request => request.status === 'APPROVED');
  
  if (approvedRequests.length === 0) {
    return 'No approved sales requests found for this period.';
  }

  // Group by technician
  const groupedByTechnician = approvedRequests.reduce((groups, request) => {
    const technicianName = request.technician_name || 'Unknown Technician';
    if (!groups[technicianName]) {
      groups[technicianName] = [];
    }
    groups[technicianName].push(request);
    return groups;
  }, {});

  // Calculate grand total
  const grandTotal = approvedRequests.reduce((total, request) => {
    return total + (parseFloat(request.total_amount) || 0);
  }, 0);

  // CSV Headers
  let csvContent = 'SALES REPORT - Approved Sales Requests\n';
  csvContent += `Generated on,${new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })}\n\n`;
  
  csvContent += 'SUMMARY\n';
  csvContent += `Total Technicians,${Object.keys(groupedByTechnician).length}\n`;
  csvContent += `Total Approved Requests,${approvedRequests.length}\n`;
  csvContent += `Grand Total,Rs. ${grandTotal.toFixed(2)}\n\n`;

  // Generate detailed data for each technician
  Object.entries(groupedByTechnician).forEach(([technicianName, requests]) => {
    const technicianTotal = requests.reduce((total, request) => {
      return total + (parseFloat(request.total_amount) || 0);
    }, 0);

    csvContent += `${technicianName.toUpperCase()} - ${requests.length} Requests - Total: Rs. ${technicianTotal.toFixed(2)}\n`;
    csvContent += 'Request ID,Company,Invoice Number,Compliant Number,Date,Product Code,Product Name,Quantity,MRP,Service Charge,Total\n';

    requests.forEach(request => {
      if (request.products && request.products.length > 0) {
        request.products.forEach((product, index) => {
          const productTotal = (parseFloat(product.quantity) * parseFloat(product.mrp)) + parseFloat(product.service_charge || 0);
          
          csvContent += `SR-${String(request.id).padStart(6, '0')},${request.company_name || ''},${request.invoice_number || ''},${request.compliant_number || ''},${new Date(request.requested_at).toLocaleDateString('en-IN')},${product.product_code || ''},"${product.product_name || ''}",${product.quantity},${parseFloat(product.mrp).toFixed(2)},${parseFloat(product.service_charge || 0).toFixed(2)},${productTotal.toFixed(2)}\n`;
        });
      } else {
        csvContent += `SR-${String(request.id).padStart(6, '0')},${request.company_name || ''},${request.invoice_number || ''},${request.compliant_number || ''},${new Date(request.requested_at).toLocaleDateString('en-IN')},No products,No products,0,0,0,${parseFloat(request.total_amount || 0).toFixed(2)}\n`;
      }
    });
    
    csvContent += `,,${technicianName} TOTAL,,,,,,,,Rs. ${technicianTotal.toFixed(2)}\n\n`;
  });

  csvContent += `GRAND TOTAL,,,,,,,,,,Rs. ${grandTotal.toFixed(2)}\n`;
  csvContent += '\nGenerated by TechFix Sales Management System';

  return csvContent;
};

/**
 * Generate and share/download sales report Excel (CSV) file
 */
export const generateSalesReportExcel = async (salesRequests) => {
  try {
    // Validate sales requests data
    if (!salesRequests || !Array.isArray(salesRequests)) {
      throw new Error('Invalid sales requests data');
    }

    // Generate CSV content
    const csvContent = generateSalesReportCSV(salesRequests);
    const fileName = `SalesReport_${new Date().toISOString().split('T')[0].replace(/-/g, '')}.csv`;

    // Create file in documents directory
    const fileUri = FileSystem.documentDirectory + fileName;
    
    await FileSystem.writeAsStringAsync(fileUri, csvContent);

    // Share the file
    await Sharing.shareAsync(fileUri, {
      mimeType: 'text/csv',
      dialogTitle: fileName,
      UTI: 'public.comma-separated-values-text'
    });

    return { 
      success: true, 
      uri: fileUri,
      fileName: fileName
    };

  } catch (error) {
    console.error('Error generating sales report Excel:', error);
    return { 
      success: false, 
      message: error.message || 'Failed to generate sales report. Please try again.' 
    };
  }
};
