# Generated by Django 6.0 on 2025-12-13 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_stock_metadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician Stock',
                'verbose_name_plural': 'Technician Stocks',
            },
        ),
        migrations.CreateModel(
            name='CourierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('received_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('items', models.JSONField(default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='couriers/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers_sent', to=settings.AUTH_USER_MODEL)),
                ('technicians', models.ManyToManyField(related_name='couriers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courier Transaction',
                'verbose_name_plural': 'Courier Transactions',
                'ordering': ['-sent_time'],
                'indexes': [models.Index(fields=['status', '-sent_time'], name='courier_api_status_617aab_idx'), models.Index(fields=['created_by', '-sent_time'], name='courier_api_created_8bc84d_idx')],
            },
        ),
    ]
