# Generated by Django 6.0 on 2025-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianstock',
            name='sheet_technician_name',
            field=models.CharField(blank=True, help_text="Technician name as it appears in Google Sheets (e.g., 'amal', 'arun kakkodi')", max_length=255, null=True),
        ),
    ]
