# Generated by Django 6.0 on 2025-12-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_api', '0002_technicianstock_sheet_technician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriertransaction',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('received', 'Received')], default='in_transit', max_length=20),
        ),
    ]
